// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: demo.proto

#include "demo.pb.h"
#include "demo.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace resumedemo {

static const char* ResumeService_method_names[] = {
  "/resumedemo.ResumeService/GetAll",
  "/resumedemo.ResumeService/Get",
};

std::unique_ptr< ResumeService::Stub> ResumeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ResumeService::Stub> stub(new ResumeService::Stub(channel, options));
  return stub;
}

ResumeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetAll_(ResumeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(ResumeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ResumeService::Stub::GetAll(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::resumedemo::ResumeSummaryList* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::resumedemo::ResumeSummaryList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAll_, context, request, response);
}

void ResumeService::Stub::async::GetAll(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::resumedemo::ResumeSummaryList* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::resumedemo::ResumeSummaryList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAll_, context, request, response, std::move(f));
}

void ResumeService::Stub::async::GetAll(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::resumedemo::ResumeSummaryList* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAll_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::resumedemo::ResumeSummaryList>* ResumeService::Stub::PrepareAsyncGetAllRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::resumedemo::ResumeSummaryList, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAll_, context, request);
}

::grpc::ClientAsyncResponseReader< ::resumedemo::ResumeSummaryList>* ResumeService::Stub::AsyncGetAllRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ResumeService::Stub::Get(::grpc::ClientContext* context, const ::resumedemo::GetRequest& request, ::resumedemo::Resume* response) {
  return ::grpc::internal::BlockingUnaryCall< ::resumedemo::GetRequest, ::resumedemo::Resume, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void ResumeService::Stub::async::Get(::grpc::ClientContext* context, const ::resumedemo::GetRequest* request, ::resumedemo::Resume* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::resumedemo::GetRequest, ::resumedemo::Resume, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void ResumeService::Stub::async::Get(::grpc::ClientContext* context, const ::resumedemo::GetRequest* request, ::resumedemo::Resume* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::resumedemo::Resume>* ResumeService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::resumedemo::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::resumedemo::Resume, ::resumedemo::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::resumedemo::Resume>* ResumeService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::resumedemo::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

ResumeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResumeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResumeService::Service, ::google::protobuf::Empty, ::resumedemo::ResumeSummaryList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ResumeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::resumedemo::ResumeSummaryList* resp) {
               return service->GetAll(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResumeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResumeService::Service, ::resumedemo::GetRequest, ::resumedemo::Resume, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ResumeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::resumedemo::GetRequest* req,
             ::resumedemo::Resume* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
}

ResumeService::Service::~Service() {
}

::grpc::Status ResumeService::Service::GetAll(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::resumedemo::ResumeSummaryList* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ResumeService::Service::Get(::grpc::ServerContext* context, const ::resumedemo::GetRequest* request, ::resumedemo::Resume* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace resumedemo
#include <grpcpp/ports_undef.inc>

